creativecommons/cccatalog-api

cccatalog-api/cccatalog/settings.py

When shortened urls, we need to ensure that it works for `ccsearch.creativecommons.org`.

Adding ccsearch.creativecommons.org to whitelist

---

cccatalog-api/cccatalog/api/views/image_views.py
cccatalog-api/test/run_test.sh
load_sample_data.sh

If a provider is missing from the `content_provider` table, the image detail view crashes. This PR adds a generic fallback for when the data is missing.

Don't crash if we're missing content provider information. #172

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/serializers/search_serializers.py
cccatalog-api/cccatalog/api/views/image_views.py
load_sample_data.sh

This PR includes:
- A more accurate page count in cases where all of the links are dead and filtered
- A new parameter `filter_dead` which allows consumers to disable dead link filtering. This is mostly for debugging purposes.
- Better sample data
- Renamed tag fields

Result count, tag search improvements #161 creativecommons/cccatalog-frontend#147

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/models.py
ingestion_server/ingestion_server/elasticsearch_models.py

We no longer use `tags_list`; all tags have been consolidated to the new format in the `tags` field.

Remove unused legacy field from the application. #181

---

cccatalog-api/cccatalog/api/views/image_views.py
cccatalog-api/cccatalog/settings.py
docker-compose.yml

We cannot display images without HTTPS on the front end without compromising the SSL security of the website, which browsers nowadays will loudly complain about and spook our users. More importantly, [there is no excuse for using insecure HTTP in 2019.](https://https.cio.gov/everything/). This causes problems for us because some of the providers in our catalog have not bothered to set up HTTPS on their servers. Since we do not want to exclude these providers entirely from our catalog or fail to render the images, we need to produce our own SSL-secured thumbnails.

Route insecure HTTP images through a proxy #191

---

cccatalog-api/requirements.txt

[CVE-2019-6975](https://nvd.nist.gov/vuln/detail/CVE-2019-6975)
[Relevant post on Django blog](https://www.djangoproject.com/weblog/2019/feb/11/security-releases/)

Upgrade Django to fix memory exhaustion vulnerability

---

cccatalog-api/cccatalog/api/utils/validate_images.py
cccatalog-api/cccatalog/api/views/image_views.py
cccatalog-api/cccatalog/settings.py

- Treat `text/html` content type as 404s
- Route all MET images through the thumbnail proxy. They're too frequently moved or broken.

Workaround MET providing incorrect status codes and content types [#198, #197]

---

cccatalog-api/cccatalog/api/utils/throttle.py
cccatalog-api/cccatalog/api/utils/validate_images.py
cccatalog-api/cccatalog/settings.py
cccatalog-api/cccatalog/urls.py

- Curb overzealous rate limit; raise limit to 7k requests per day with bursts of 60/min. The 1000 daily request rate limit was impacting too many users.
- Proxy all IHA thumbnails. They're too small. Revisit the MET at a later date.

Burst and sustained rate limit

---

.travis.yml
cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/licenses.py
cccatalog-api/cccatalog/api/serializers/search_serializers.py
cccatalog-api/test/api_live_integration_test.py

- Add CC0 to 'all-cc' license type
- Correctly interpret multiple license types to better match user expectations. Specifying `commercial,modification` should return results where commercial AND modification is allowed, not commercial OR modification.

Fix license type filters #202

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/licenses.py
cccatalog-api/cccatalog/api/models.py
cccatalog-api/cccatalog/api/serializers/image_serializers.py
cccatalog-api/cccatalog/api/views/image_views.py
cccatalog-api/pytest.ini
cccatalog-api/requirements.txt
cccatalog-api/test/api_live_integration_test.py

- Add attribution field to response. Example:
```
{
"attribution": "\"Dish\" by A. Douglas Nash Corporation is licensed under CC-BY 3.0. To view a copy of this license, visit https://creativecommons.o
rg/licenses/by/3.0/.", 
...
}
```
- Add `license_url` field to image detail response.

Add available attribution information to API response.

---

ingestion_server/ingestion_server/elasticsearch_models.py
ingestion_server/ingestion_server/indexer.py
ingestion_server/test/integration_tests.py

Addressing #112, this PR adds in:
1. an explicit `removed_from_source` field during the `Image` elastic_search_model setup/
2. A check to see if the `removed_from_source` field is `False` and then only append to documents.
Things to add:
1. Test to check for the same.
@aldenstpage: Would love to hear your thoughts on this.

#112: Exclude results with removed_from_source set to True

---

.cc-metadata.yml

Add metadata file to display this repo as a "featured" repo on the CC Open Source site (feature still in progress).

Add metadata for CC Open Source site.

---

ingestion_server/README.md

This Pr fixes issue [228](https://github.com/creativecommons/cccatalog-api/issues/228) . It updates readme of ingestion folder to fixed broken image link of how ingestion works

Updated Ingestion Readme to fix broken image link 

---

README.md

This commit addresses issue #221 by adding some instructions to the `README.md` file, outlining what to do in case a very commonly-faced error with Elastic Search `mmapfs` pops up.

Add instructions regarding vm.max_map_count to ensure ElasticSearch starts up correctly

---

cccatalog-api/Dockerfile
cccatalog-api/cccatalog/api/utils/watermark.py
cccatalog-api/cccatalog/api/views/image_views.py
cccatalog-api/requirements.txt
cccatalog-api/test/api_live_integration_test.py

We use PIL to produce watermarked images. Most PIL transformations discard EXIF metadata; to work around this, extract the EXIF before we do anything to the image and add it back after the watermark has been generated.

Prevent PIL from destroying exif metadata when we watermark images #238

---

cccatalog-api/Dockerfile
cccatalog-api/cccatalog/api/utils/ccrel.py
cccatalog-api/cccatalog/api/utils/watermark.py
cccatalog-api/cccatalog/api/views/image_views.py
cccatalog-api/requirements.txt

Related to #232. I added embedded ccREL through XMP to watermarked images. Here's an example of the raw XML:
```
web_1               | <?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
web_1               | <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Exempi + XMP Core 5.5.0">
web_1               |  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
web_1               |   <rdf:Description rdf:about=""
web_1               |     xmlns:tiff="http://ns.adobe.com/tiff/1.0/"
web_1               |     xmlns:xmp="http://ns.adobe.com/xap/1.0/"
web_1               |     xmlns:exif="http://ns.adobe.com/exif/1.0/"
web_1               |     xmlns:cc="http://creativecommons.org/ns#"
web_1               |     xmlns:xmpRights="http://ns.adobe.com/xap/1.0/rights/">
web_1               | …
```

Embed ccREL metadata into watermarked images using XMP #232

---

cccatalog-api/cccatalog/api/serializers/image_serializers.py
cccatalog-api/cccatalog/api/utils/watermark.py
cccatalog-api/cccatalog/api/views/image_views.py

`embed_metadata` controls whether we embed ccREL XMP metadata inside of a watermarked image.
`watermark` controls whether the frame is drawn at all.
In situations where both embed_metadata=False and watermark=False, the caller should avoid using the endpoint and instead link directly to the image in order to save cycles on the server.

embed_metadata and watermark parameters #243

---

ingestion_server/ingestion_server/cleanup.py
ingestion_server/ingestion_server/indexer.py
ingestion_server/ingestion_server/ingest.py

CC Catalog stores raw data from upstream content providers that can be inappropriate for production use. Now, every time we import data from CC Catalog, perform some cleanup of the data as we copy it into the API database. By setting values in _cleanup_config, you can have fine grained control over which fields from which providers and which tables get cleaned up.
Right now, Ingestion Server is capable of fixing malformed URLs, deleting blacklisted tags, and deleting machine generated tags whose confidence falls under a 90% threshold. Adding more cleanup functions is easy.
I think we can feasibly run this on the entire 285MM dataset. I'll have to run it in testing to be sure.
We should also switch Ingestion Server to an instance with more threads available so it can take advantage of …

Implement cleanup module to tidy up raw data from upstream CC Catalog #244

---

cccatalog-api/cccatalog/api/utils/ccrel.py

This prevents us from overwriting existing XMP rights information + ccREL, in the event that either are present.

Make sure XMP fields don't already exist before writing them

---

ingestion_server/ingestion_server/cleanup.py
ingestion_server/ingestion_server/ingest.py

Fixes creativecommons/ccsearch-infrastructure#42.
- Set cur.itersize so psycopg2 doesn't try to load the entire table into memory at once (setting fetchmany(size=...) was not enough to prevent this)
- Set a primary key index before attempting to clean the data in the temporary table; otherwise, the time to update a single record grows linearly with the size of the table. This bug didn't come up in testing, which only has a few thousand records, but is definitely unworkable on a production-sized table.

Optimize ingestion cleanup set so it scales to realistic workloads.  creativecommons/ccsearch-infrastructure#42

---

.travis.yml
ingestion_server/Dockerfile
ingestion_server/Pipfile
ingestion_server/Pipfile.lock
ingestion_server/requirements.txt

As mentioned in the discussions preceding the merge of PR #225, the ingestion server has also been ported to use Pipenv for its dependency management needs. The corresponding `Dockerfile` and `.travis.yml` have also been updated to reflect these changes.

Porting Ingestion server to Pipenv

---

cccatalog-api/cccatalog/api/views/image_views.py

The front end needs a way to identify individual providers. `provider` exposes the formatted name, while `provider_code` exposes the identifier.

Expose provider_code field

---

ingestion_server/ingestion_server/elasticsearch_models.py

Elasticsearch keyword matches are case sensitive, and some providers have different casing in their license (the MET has both 'cc0' and 'CC0'. Make all license types lowercase to enforce consistency.
Reindexing is required for this change to take effect. @brenoferreira fyi

Fix casing inconsistency breaking license filters for the MET

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/test/search_qa_test.py
ingestion_server/ingestion_server/cleanup.py
ingestion_server/ingestion_server/elasticsearch_models.py
ingestion_server/ingestion_server/es_mapping.py
ingestion_server/ingestion_server/indexer.py

- Disable `constant_score` query filter. This was used to prevent repetitive titles from being disproportionately highly ranked by Elasticsearch's [BM25 algorithm](https://www.elastic.co/guide/en/elasticsearch/guide/master/pluggable-similarites.html) (e.g. an image titled "Nature nature nature nature nature" would be at the top of the results for any "nature" query. This situation was very common across many queries.) While using `constant_score` solved the repetition problem, it really kneecapped the quality of our search in other ways, as it disables a lot of other desirable functionality used to rank search queries.
- Set `title` field mapping `similarity = boolean`. This disables full-text search ranking for this field specifically and leaves the rest of the fields untouched. That …

Phrase relevance improvements #258

---

cccatalog-api/cccatalog/api/utils/validate_images.py

Fixes #280.
To detect broken links, the server will send an HTTP HEAD request to each URL in the search results, and then cache them for some long period of time. Each request has a timeout of 200ms. This caused problems for image servers geographically distant from our API servers. Museums Victoria, for instance, is hosted in Australia, and it takes nearly 1.5 seconds to receive a response from them, which caused the server to think all of their links were dead. By increasing the timeout to 2 seconds, we can ensure that this edge case doesn't occur.
Because validation results are cached, there shouldn't be a big impact on API performance in the long term.

Increase image validation timeout

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/serializers/search_serializers.py
cccatalog-api/cccatalog/api/views/image_views.py
cccatalog-api/cccatalog/urls.py
cccatalog-api/test/api_live_integration_test.py

Fixes #205
Allow searching by provider, without search terms, using the `/image/provider/<provider_identifier>` endpoint. This does not allow comprehensive downloading of the largest collections; only the first ~10,000 results can be accessed through this endpoint. As with our `/image/search` endpoint, this is not intended for bulk download.

Browse by provider

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/serializers/search_serializers.py
cccatalog-api/cccatalog/api/views/image_views.py

As requested by Breno; users may want to further refine their `/image/browse` results by license or license type.

Add optional license filters to browse by provider endpoint.

---

cccatalog-api/cccatalog/api/controllers/search_controller.py

Relates to #303. 
Instead of using the score of the best matching field to rank results, prefer results with matches in multiple fields. It's not a panacea for search relevance, but initial testing in `ccsearch-dev` indicates that there is some improvement with our most egregious examples of low quality search results (flamingos, DNA).
See the `type` setting in the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) for more information.

Use 'most_fields' instead of 'best_fields' 

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/serializers/search_serializers.py
cccatalog-api/cccatalog/api/views/image_views.py
cccatalog-api/cccatalog/urls.py

Fixes #286.
Given a UUID, find images similar to the image. Similar images are ranked by the amount of overlap between `tags`, `title`, and `creator`. Likely candidates for similar images include other images from the same artist or user which include similar tags or titles (e.g. the related images for UserFoo's picture of a fountain in Rome likely include other images from that same trip to Rome).
This feature is in api-dev for testing; see `api-dev.creativecommons.engineering/image/related/<uuid>`

Related images endpoint

---

ingestion_server/ingestion_server/cleanup.py

SELECTing by provider is slow on the downstream temporary table because there are no indexes at that point in the process. It requires doing a full table scan on 300MM+ URLs.

Use the upstream database for finding sample URLs for TLS testing.

---

analytics/README.md
cccatalog-api/cccatalog/api/utils/throttle.py
cccatalog-api/cccatalog/settings.py

Don't throttle requests from our own network. This allows us to run our static site renderer without throttling it needlessly.
The nginx proxy in front of the SSR will need to be configured to throttle requests to prevent abuse, otherwise it would essentially allow users to crawl the catalog through the frontend.

Exempt request from rate limiting if it originates from our internal network

---

cccatalog-api/cccatalog/api/utils/throttle.py
cccatalog-api/cccatalog/settings.py

Internal clients can register their IP address in Redis to prevent being throttled.
Example self-registration:
```
redis-cli -h ${redis_url} sadd ip-whitelist $IPV4_ADDRESS
```
The 'trusted network' configuration idea was flawed; requests to the API are resolved by their public IPs, even when they're coming from our public network. To make the requests from the private network would mean setting up a separate internal load balancer, a private DNS zone, and some more frontend logic to make use of it. Rather than go that route, let's just have the front end servers self-add themselves to the Redis whitelist.

Implement the trusted IP whitelist in Redis

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/test/api_live_integration_test.py

Related to https://github.com/creativecommons/cccatalog-frontend/issues/474
Elasticsearch `query_string` queries uses double quotes to indicate exact matches. A single quote on its own is an unfinished exact match query, which is an error.
In order to make it a little harder for users to shoot themselves in the foot, we can escape quotation marks if any of them are unmatched.

Ignore invalid use of quotation marks

---

cccatalog-api/cccatalog/api/views/image_views.py

Fixes #263.
See https://github.com/creativecommons/ccsearch-infrastructure/commit/0987889c80c7804b924065ee8f518227a3c9f9ce; there was an environment issue preventing the view count tracking job from running.

Add track_model_views decorator back to image detail views

---

cccatalog-api/cccatalog/api/serializers/image_serializers.py
cccatalog-api/cccatalog/api/serializers/search_serializers.py
ingestion_server/ingestion_server/elasticsearch_models.py
ingestion_server/ingestion_server/es_mapping.py

Fixes #306 
Add "height" and "width" parameters to search results and detail views. Since not all integrated upstream APIs expose this, not all images will have this information available.

Expose height and width of images when available

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/serializers/search_serializers.py

Fixes #338 
Allow filtering searches by multiple file extensions simultaneously instead of just one.

Add support for filtering by multiple extensions

---

ingestion_server/ingestion_server/es_mapping.py

Fixes #355 
Added a field, similarity in the mappings file under description to ensure similarity checking is boolean
---
Version 1.1
Suite D4700
license and I have …

Added similarity field in mappings

---

cccatalog-api/Pipfile
cccatalog-api/Pipfile.lock
cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/serializers/search_serializers.py
cccatalog-api/cccatalog/settings.py
docker-compose.yml
ingestion_server/Pipfile
ingestion_server/Pipfile.lock
ingestion_server/ingestion_server/cleanup.py
ingestion_server/ingestion_server/elasticsearch_models.py
ingestion_server/ingestion_server/es_mapping.py
ingestion_server/ingestion_server/indexer.py
ingestion_server/ingestion_server/ingest.py
misc/README.md
misc/gen_popularity.py

Index popularity data in Elasticsearch and use it as a ranking factor if POPULARITY_BOOST is enabled (disabled by default for now).
Some providers give us stats like "views", "comments", and "likes", which we can use as a ranking factor. This is expected to be stored in the `meta_data` field in Postgres under the key `popularity_metrics`.
We're going to need popularity data in production for at least one provider in order to be able to fine-tune it in a useful way (adjusting boost factor and other parameters, preventing non-social results from being drowned out, comparing with/without popularity boosting in our dev environment). All of that is blocking on pulling popularity data and writing it to the `meta_data` column in creativecommons/cccatalog. I expect to have to do some additional …

Popularity boosting (with caveats)

---

cccatalog-api/cccatalog/api/licenses.py
cccatalog-api/cccatalog/api/models.py

Fixes https://github.com/creativecommons/cccatalog-api/issues/384
PDM license links aren't formatted like the others; add a special exception for linking to the PDM deed.

Fix broken PDM license link

---

cccatalog-api/cccatalog/api/serializers/image_serializers.py
cccatalog-api/cccatalog/api/serializers/search_serializers.py

Fixes #387.
Return the `license_url` in search endpoint in addition to image detail views.

Return license URL in search response

---

ingestion_server/ingestion_server/cleanup.py
ingestion_server/test/unit_tests.py

Related to #253 
Add some unit tests of the cleanup step and fix a logic error that was preventing blacklisted license tags from being filtered out.

Fix logic error preventing tag filtering from working properly

---

cccatalog-api/cccatalog/api/serializers/search_serializers.py
ingestion_server/ingestion_server/categorize.py
ingestion_server/test/unit_tests.py

Related to #340 
Remove the `vector` category described in the requirements for #340; it's exactly equivalent to `illustration`.

Remove redundant image category

---

ingestion_server/ingestion_server/indexer.py

Fixes #400 
Exclude images where the `license_version` is missing. This is a workaround until we fix the missing or incorrect data in the pipeline.

Don't index images where the license_version is not known.

---

cccatalog-api/cccatalog/api/utils/exceptions.py
cccatalog-api/cccatalog/api/views/image_views.py

Handles search phase execution exceptions that throws an error 500, instead of an InputError.
Fixes [406](https://github.com/creativecommons/cccatalog-api/issues/406)
Without handling the errors, the API crashes.
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, …

Handles search phase execution exceptions

---

cccatalog-api/cccatalog/api/licenses.py
cccatalog-api/cccatalog/api/serializers/image_serializers.py
ingestion_server/ingestion_server/elasticsearch_models.py
ingestion_server/ingestion_server/es_mapping.py
ingestion_server/ingestion_server/indexer_worker.py
ingestion_server/test/unit_tests.py

Fixes https://github.com/creativecommons/cccatalog-api/issues/415
Our original model assumed that a CC license has the same terms across all languages. This is only true for versions 4.0 and higher. All other licenses have different terms in each jurisdiction, so we need to make sure that we provide a link to the correct license in those cases.
If we have the exact `license_url` for an image upstream (which might include the jurisdiction-specific URL), use it. Otherwise, we will try to generate the `license_url` from the `license` and `license_version` fields.

Correctly handle international jurisdiction license URLs

---

cccatalog-api/Pipfile.lock
cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/test/v1_integration_test.py

Fixes #410.
Make the change of parser from 'query_string' to 'simple_query_string' according to requested in #410.
---
<details>
<summary>Developer Certificate of Origin Version 1.1</summary>
Suite D4700
of my knowledge, is covered under an appropriate open …

Change query string parser type

---

cccatalog-api/cccatalog/api/controllers/search_controller.py

Related to https://github.com/creativecommons/ccsearch-infrastructure/issues/119
We're having occasional issues with Elasticsearch getting stuck on a query in production. Since we are unable to set a global timeout due to limitations of AWS Elasticsearch Service, it seems reasonable to set a timeout on search queries instead.

Add 7 second search timeout to kill off unhealthy requests

---

.github/workflows/IssueAndPR.yml

PRs from outside contributors will fail here because of the insufficient permission, which might be confusing.
This PR make sure that this action will not cause surprising fails.
---
Version 1.1
Suite D4700
of my knowledge, …

workflow: Add continue-on-error to avoid confusion

---

README.md

Fixes #462 
The link to the cccatalog-frontend is incorrect.
It points to cccatalog which has been changed.
```
Version 1.1
Suite D4700
license and I have the right …
```

Fix incorrect link to cccatalog-frontend in Readme

---

cccatalog-api/cccatalog/api/controllers/search_controller.py

I think this is the culprit behind Elasticsearch getting backed up and overloaded every once in a while.
After the usual Elasticsearch incident took place today on our brand-spanking-new EC2 cluster, I went into our new cluster's logs (not previously possible with the managed version...) and saw lots of slow queries that looked like this:
```
{"type": "server", "timestamp": "2020-04-30T23:13:39,433Z", "level": "DEBUG", "component": "o.e.a.s.TransportSearchAction", "cluster.name": "ccsearch-prod", "node.name": "172.30.1.113", "message": "[image-64585e2af24744819d29202556df7396][5], node[ON58EM7CQ6GN1uClGp5cxA], [R], s[STARTED], a[id=27Q4nL3nRsu2Uja23clnKw]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[image], indicesOptions=IndicesOptions[ignore_unavailable=false, …
```

Rewrite source filtering logic

---

cccatalog-api/cccatalog/api/controllers/search_controller.py

Related to https://github.com/creativecommons/cccatalog-api/pull/483
We need to keep track of the time it takes for Elasticsearch to process a request so we can monitor growing workload complexity.

Efficient exclusion

---

ingestion_server/ingestion_server/es_mapping.py
ingestion_server/ingestion_server/indexer.py

Related to https://github.com/creativecommons/ccsearch-infrastructure/issues/120
This increases the shard count of our cluster and the wait_for_status timeout.
Shards are used to distribute data evenly between Elasticsearch nodes. They should be between 10-50gb each; we are getting too close to 50gb, and our dataset is growing. Increasing the count to 18 shards will reduce the data set to about 25gb per shard. See [How many shards should I have in my Elasticsearch cluster?](https://www.elastic.co/blog/how-many-shards-should-i-have-in-my-elasticsearch-cluster)
During indexing, we create a temporary index in parallel with production to populate the refreshed documents. We disable shard replicas during index to reduce the CPU load of indexing. When shards are re-enabled, it takes time …

Increase shard count

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/wsgi.py
docker-compose.yml
load_sample_data.sh

`get_providers` is called on the "about" page in CC Search, which returns statistics about the number of images each source contributes to the catalog. Generating this query is expensive and needs to be cached for as long as possible, as it can block other queries from running.
Instead of caching it for 10 seconds, we should cache it on the order of minutes. This PR increases it to 20 minutes.
The longer cache period creates a race condition in the unit tests, so we have to manually unset it after test data has been loaded. In production conditions, it won't matter if the source cache is 20 minutes stale.

Cache source count for 20 minutes instead of 10 seconds

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/utils/throttle.py
cccatalog-api/cccatalog/api/views/site_views.py

This makes a few adjustments to a community PR to make it more suitable for production conditions.
- Requests towards the thumbnail proxy should not be assigned the default throttle class, or else it will count towards the user's overall rate limit (which will result in 429 errors being thrown for no reason).
- Requests to the thumbnail proxy must be SSL secured in order to show up on the front end.
- If the thumbnail proxy is unreachable or otherwise cannot handle an image, we should explicitly return an internal server error.

Thumbproxy productionization

---

cccatalog-api/cccatalog/api/controllers/search_controller.py

The [/v1/sources](https://api.creativecommons.engineering/v1/sources) endpoint is expensive and used heavily by clients. It needs to count every single image in our catalog in milliseconds. The expense of this endpoint is causing problems in our new Elasticsearch cluster architecture, which trades off CPU cores (important for this query specifically, but unimportant for searches) for storage IO performance (critical for searches). The cluster can hang for several seconds while this value is computed, which can result in searches timing out.
To cope with this, we cache the value server-side for a long period of time (20 minutes). The problem is that when this cache expires, there can be a [thundering herd](https://en.wikipedia.org/wiki/Thundering_herd_problem) effect as every one of our …

Optimize /v1/sources

---

ingestion_server/ingestion_server/indexer.py

Instead of waiting for replica shards to initialize, we will direct searches to the new search index right after data has been successfully loaded.
Please see the tagged issue for a more detailed background on why this change is necessary and what prompted it.

Don't wait for replica shards.

---

ingestion_server/ingestion_server/indexer.py

During bulk indexing, Elasticsearch can become overwhelmed with writes and reject indexing requests. There could also be rare cases where the upstream data is malformed in a way that prevents the indexer from uploading a particular chunk of data. Either case causes the indexer worker to stop indexing its batch.
If a bulk indexing request is rejected for any reason, we will retry with exponential backoff. If `max_attempts` is exceeded, this batch will be skipped and we will continue indexing the rest of the data.
Once we have some more detailed logs, we will be able to implement better handling of malformed rows and discard them from the upload batch.

Retry unsuccessful bulk uploads.

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
ingestion_server/ingestion_server/distributed_reindex_scheduler.py
ingestion_server/ingestion_server/indexer.py

Early on in this project, I set `max_retries` and `timeout` in the ES constructor to large values thinking that they controlled only connection retries/timeouts. In reality, it applies to all calls made in the client. This caused the problems described here: https://github.com/creativecommons/cccatalog-api/pull/496 .
We need to not retry Elasticsearch queries so aggressively. 10 seconds is a pretty long time, so one retry should be sufficient. In the context of indexing, we don't want to leave retries to the client at all.
This PR fixes those timeouts and restores the `wait_for_status` check.

Adjust Elasticsearch retries and timeouts

---

ingestion_server/ingestion_server/indexer.py

See https://github.com/creativecommons/cccatalog-api/pull/498; now that we aren't timing out after five minutes, we can wait for replica shards to be reinitialized (which takes about an hour with our current workload).

Restore wait_for_status check

---

ingestion_server/ingestion_server/ingest.py

Images that we choose to deindex (such as for a DMCA takedown or other legal matter) can be added back to our database by the weekly ingestion job. The result is that, although the image will not appear in our search results, someone with the direct URL to the image can view the "deindexed" work after the ingestion process runs.
To fix this, we need to exclude images in the `api_deletedimages` table (populated by our reporting interface) from the ingestion process.
I verified this feature manually by taking the following steps:
1. Start the server with docker-compose.
2. Set up a Django superuser and go to the /admin page.
3. Delete an image through the Report Images UI.
4. Reingest the data with `curl -XPOST localhost:8001/task -H "Content-Type: application/json" -d '{"model": "image", …

Exclude deindexed images from the ingestion process

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/views/site_views.py

This PR removes file extensions from thumbnail URLs. This was causing problems rendering views containing images without a file extension in their upstream URL. There is no need to specify the file extension for thumbnail URLs since browsers determine the format of images by the `Content-Type` header.

Remove extension parsing logic

---

ingestion_server/ingestion_server/cleanup.py

This change filters out malformed tags during the cleanup process. If the `name` field is missing, the tag will be removed during the cleanup process.

Add handling for malformed tags in cleanup process

---

cccatalog-api/cccatalog/api/licenses.py
cccatalog-api/test/v1_integration_test.py

We can override `license_url` in `cccatalog` by setting a direct URL in the `meta_data` column. If it is set to `null`, the API server faithfully serves it up. Instead, we should fall back to the generated license URL.

Ignore license_version = null overrides

---

cccatalog-api/cccatalog/api/serializers/image_serializers.py

Fixes https://github.com/creativecommons/cccatalog-api/issues/523 by @aldenstpage 
the size parameter was documented but not visible in API docs.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```

fix bug : size parameter was not getting displayed in API docs.

---

cccatalog-api/cccatalog/settings.py
cccatalog-api/test/run_test.sh
docker-compose.yml

Fixes #519 by @TimidRobot 
Moves the default value of `SECRET_KEY` to `docker-compose.yml`
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in the file; …
```

Moved default value of django secret key to docker compose

---

cccatalog-api/cccatalog/api/views/image_views.py
cccatalog-api/cccatalog/settings.py

We proxy insecure HTTP images through our internal proxy to make sure everything is SSL protected. Changing to internal thumbnailing broke this functionality; it would result in the `url` including a reference to `localhost`.

Fix broken HTTP images on detail pages

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/models.py
cccatalog-api/cccatalog/api/serializers/image_serializers.py
cccatalog-api/cccatalog/api/views/site_views.py
ingestion_server/ingestion_server/authority.py
ingestion_server/ingestion_server/categorize.py
ingestion_server/ingestion_server/cleanup.py
ingestion_server/ingestion_server/elasticsearch_models.py
load_sample_data.sh

The display of different sources will be driven by the `source` field instead of `provider`. `provider` will now be used to display the originating platform.

Use source field instead of provider

---

ingestion_server/ingestion_server/ingest.py

This change removes an unnecessary dependency on an upstream column that has been removed from the cccatalog schema. There's a workaround for the removed view_count column also, which will be removed from the API later in https://github.com/creativecommons/cccatalog-api/issues/540.
A sequential ID column is required for the indexer process to partition records between indexing workers. Instead of using the ID column from the catalog, it will create a column in the temporary ingestion table.

Upstream schema fix

---

cccatalog-api/cccatalog/api/controllers/search_controller.py
cccatalog-api/cccatalog/api/serializers/image_serializers.py
cccatalog-api/cccatalog/settings.py

Thumbnails should always be routed through our image proxy. To do this consistently, move proxying logic from view post-processing to serialization layer.
FYI @makkoncept

Proxy thumbnails during serialization instead of through post-processing

---

.travis.yml
cccatalog-api/Pipfile
cccatalog-api/Pipfile.lock
cccatalog-api/cccatalog/settings.py
cccatalog-api/cccatalog/wsgi.py
docker-compose.yml

When an administrator uploads a source logo to CC Search, it should be stored in S3 instead of on the disk of the server. Externalizing the logos from the server allows them to persist between releases.

Upload logos to s3

---

ingestion_server/ingestion_server/cleanup.py

We no longer display third party thumbnail URLs, so we shouldn't waste time cleaning them up.

Skip validation of thumbnail URLs

---

cccatalog-api/cccatalog/api/serializers/image_serializers.py

Our thumbnail proxy isn't correctly configured to preserve aspect ratios, resulting in all images in the search results being squares. This change fixes that issue and also sets the thumbnail resolution instead of taking imageproxy's default.
More information about imageproxy parameters can be found [here](https://github.com/willnorris/imageproxy).

Preserve aspect ratio in thumbnails

---

cccatalog-api/cccatalog/api/models.py

Rename "Filter content to "Hide content" in admin UI

---

cccatalog-api/cccatalog/api/controllers/search_controller.py

Disabled sources can appear in image recommendations. We need to factor out the filtering logic to be reusable in other search endpoints.
This also reduces the amount of time that we cache filters to alleviate pain caused by https://github.com/creativecommons/cccatalog-api/issues/583. We'll cache filtered sources for 30 seconds instead of 20 minutes.

Exclude filtered sources from recommendations endpoint
