creativecommons/cccatalog-api

cccatalog-api/cccatalog/api/views/image_views.py
Don't adjust result count after dead link filtering unless there is only a single page.
=> Filter result count

cccatalog-api/cccatalog/api/controllers/search_controller.py, cccatalog-api/cccatalog/api/views/image_views.py, cccatalog-api/test/api_live_integration_test.py
=> Expose lucene query syntax #204

cccatalog-api/cccatalog/api/serializers/search_serializers.py
=> [#298] Fix off-by-one error in pagesize param

cccatalog-api/cccatalog/api/controllers/search_controller.py
Fixes creativecommons/cccatalog-frontend#402
Explanation: https://medium.com/@lefloh/elasticsearch-and-case-sensitive-term-queries-6f6c516aebed
=> Fix issue causing certain providers to not show up in the browse view

ingestion_server/ingestion_server/cleanup.py
Related to efforts to improve search relevance.
This will filter out low-value tags that are responsible for several low quality Flickr results, like 'flamingo' and 'aardvark'.
=> Enhance the tag blacklist

cccatalog-api/cccatalog/api/utils/view_count.py
=> Use identifier instead of deprecated id field for view counts

cccatalog-api/cccatalog/api/controllers/search_controller.py, cccatalog-api/cccatalog/api/serializers/search_serializers.py, cccatalog-api/test/api_live_integration_test.py, ingestion_server/ingestion_server/elasticsearch_models.py, ingestion_server/ingestion_server/es_mapping.py
Fixes #338
Allow users to filter by file type.
=> File type filters

cccatalog-api/cccatalog/api/controllers/search_controller.py, cccatalog-api/cccatalog/api/views/image_views.py
Fixes #363
Unescaped special characters are not handled which leads to server side error. We should catch the exception and return an appropriate validation message to client.
---
Version 1.1
Suite D4700
of my knowledge, is …
=> Raise exception on unescaped query string image search

README.md
Fixes #372 (partially)
This would make the setup process easier for beginners without knowledge of docker.
---
Version 1.1
Suite D4700
license and I have the right …
=> add reference to Docker Compose docs in README.md

cccatalog-api/cccatalog/api/controllers/search_controller.py, cccatalog-api/cccatalog/api/serializers/search_serializers.py, ingestion_server/ingestion_server/categorize.py, ingestion_server/ingestion_server/elasticsearch_models.py
Related to #340. See comments on the issue
=> Prototype proposed image type feature

CONTRIBUTORS.md, cccatalog-api/cccatalog/api/utils/exceptions.py, cccatalog-api/cccatalog/api/views/image_views.py
Contains changes from #411 + CONTRIBUTORS.md update
=> Community searchphase

cccatalog-api/cccatalog/api/controllers/search_controller.py, cccatalog-api/cccatalog/api/serializers/image_serializers.py, cccatalog-api/cccatalog/api/views/image_views.py
Fixes #429 
This pull request addresses the requirement of a suggestion field in the result image search to facilitate the new feature wherein the handling of misspelled searches can be done more efficiently.
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to …
=> Implementing suggestions for search

.github/CODEOWNERS, CODEOWNERS
---
Version 1.1
Suite D4700
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under …
=> Added CODEOWNERS file

.github/workflows/IssueAndPR.yml
Fixes #438 
---
Version 1.1
Suite D4700
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part …
=> Updated GitHub Action to point to the right column

README.md
I'm using this PR also to test the GitHub Action.
---
Version 1.1
Suite D4700
license and I have the right under that license to submit that
work with …
=> Deleted inaccurate "Project Status" in README

cccatalog-api/cccatalog/api/utils/exceptions.py
Fixes #452
The issue describes an inconsistency between the `400` response parameters of the [`image_search` api](https://api.creativecommons.engineering/v1/images) and the [documentation for the same](https://api.creativecommons.engineering/v1/#operation/image_search).
| docs     | response     | Description of the parameter            |
| -------- | ------------ | --------------------------------------- |
| `error`  | `error_type` | A string describing the type of error   |
| `fields` | `field`      | The list of fields that cause the error |
In this [comment](https://github.com/creativecommons/cccatalog-api/pull/453#discussion_r391738976), @makkoncept reasoned that it would be better to keep the docs the same.
I noticed that the `detail` parameter was a little difficult to interpret. …
=> Change response parameters for `/images` API

cccatalog-api/cccatalog/api/controllers/search_controller.py, cccatalog-api/cccatalog/api/views/site_views.py, cccatalog-api/cccatalog/settings.py, cccatalog-api/cccatalog/urls.py, cccatalog-api/test/v1_integration_test.py
Fixes #444
I accidentally deleted my fork during these days, so I have to open another PR.
---
Version 1.1
Suite D4700
license and I have the right under that …
=> Hide the thumbnail proxy from end-users

cccatalog-api/cccatalog/urls.py
related to https://github.com/creativecommons/cccatalog-api/issues/491
as this documentation is focused for developers
1. added system architecture of the repository so one doesn't has to visit
github for the diagram.
2. also added rest api code for clear understanding.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution …
```
=> ADDING Architecture Diagram AND REST API CODES.

CONTRIBUTING.md
related to https://github.com/creativecommons/cccatalog-api/issues/491
in the contribution file the link were pointing to CC Frontend project instead
of CC Catalog API.
also the section for running test was not for this repository.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) …
```
=> fixed wrong links and added running test documentation.

.github/dependabot.yml
Fixes #532 by @nimishbongale
Checks in a `.github/dependabot.yml` for configuring the dependabot.
Dependabot is now native to github, provides a handy automatic way of handling dependency upgrades.
Dependabot has been successfully configured in my [fork](https://github.com/nimishbongale/cccatalog-api/runs/771462080).
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Configured Dependabot (Fixes #532)

.github/CODEOWNERS
<details>
```
Version 1.1
Suite D4700
license and I have the right under that license to submit that
work with …
```
=> Added collaborators to CODEOWNERS
